### ISSUE TITLE
Consistency (or merge) between `kubozer.conf.js` and `webpack.config.js`

### ISSUE THREAD

**Issue by LasaleFamine** [contactlab/kubozer#16]
We need a better consistency between the two configuration files: currently we are specifying the `output.path` and `output.filename` within the `Webpack` configuration and also the `buildFolder` and `buildJs` within the `Kubozer` configuration. 

During the build, the `webpack` conf is overwritten by our configuration like so:  
```javascript
// builder.js
this.webpackConfig.output.path = this.config.buildFolder;
this.webpackConfig.output.filename = this.config.buildJS;
```
Possible solutions: 
- use the **Webpack** conf to get the `path` and `filename` but check if the `buildFolder` is the same of the `path`. Also remove the property `buildJs` from the `kubozer` conf.
- (:star:) merge the two configuration into a new one only for **Kubozer**. This will allow to use Webpack without worries about conflict with the Kubozer configuration

**Comment by LasaleFamine** [comment]
Proposal solution: 

- check for `buildFolder` and `buildJS` within the `kubozer.conf.js`. **If present, ovveride the webpack `output.path` and `output.filename` (and notify the user about the choice)**.  
-  if `buildFolder` and `buildJS` are **NOT** present, **simply use `output.path` and `output.filename` from webpack configuration  (and notify the user about the choice)**.  
- if both in Kubozer conf and webpack conf the properties are not present, **throw an error**

**Comment by LasaleFamine** [comment]
Other proposal: merge both configuration and rewrite current `kubozer.conf.js`

```javascript
module.exports = {
	main: {
		workspace: './test/workspace',
		sourceAppFolder: './test/src-test',
		buildAppFolder: './test/build',
		buildJsFile: 'bundle.min.js',
		buildCssFile: 'style.min.css',
		assetsFolder: './test/src-test/assets',
		sourceCssFiles: ['/test.css'],
		manifest: true
	},
	bump: {
		files: [
			'./test/src-test/package.json',
			'./test/src-test/manifest.json'
		]
	},
	copy: [
		{
			baseFolder: 'assets',
			items: [
				'imgs-others'
			]
		}, {
			baseFolder: 'bundles',
			items: [
				''
			]
		}
	],	
	replace: {
		css: {
			files: 'index.html',
			commentRegex: ['<!--styles!--->((.|\n)*)<!--styles!--->'],
			with: ['assets/style.min.css']
		},
		js: {
			files: 'index.html',
			commentRegex: ['<!--js!--->((.|\n)*)<!--js!--->'],
			with: ['bundle.js']
		}
	}
	vulcanize: {
		srcTarget: 'index.html',
		buildTarget: 'index.html',
		conf: {
			stripComments: true,
			inlineScripts: true,
			inlineStyles: true,
			excludes: ['bundle.js']
		}
	},
	webpack: {
		entry: './test/src-test/app/index.js',
		output: {
			// Make sure to use [name] or [id] in output.filename
			//  when using multiple entry points
			path: './test/src-test/',
			filename: 'bundle.js'
		},
		devtool: 'source-map',
		module: {
			loaders: [{
				test: /\.js?$/,
				// exclude: /(node_modules|bower_components)/,
				exclude: ['node_modules', 'test/bundle.js', 'test/build'],
				loader: 'babel-loader',
				query: {
					presets: ['es2015'],
					plugins: ['transform-es2015-spread', 'syntax-object-rest-spread', 'transform-object-rest-spread']
				}
			}]
		}
	}
};
```

We can specify that during the `build` process (not during an hypothetical `watch` method) the `output.path` and `output.filename` will be overwritten.

**Comment by pferretti** [comment]
+1 for your first proposal. I think that the inclusion of Webpack configuration into Kubozer configuration cold be a mess.

**Comment by LasaleFamine** [comment]
CC: @contactlab/contactlab-frontend-engineers

**Comment by LasaleFamine** [comment]
Thinking to both solutions, I have another one: 

Maintaining the second structure of `kubozer.conf` but removing `webpack` configuration and also the property `buildJsFile` from it.

```javascript 
// kubozer.conf.js
module.exports = {
	workspace: './test/workspace',
	sourceFolder: './test/src-test',
	buildFolder: './test/build',
	buildCssFile: 'style.min.css',
	assetsFolder: './test/src-test/assets',
	sourceCssFiles: ['/test.css'],
    manifest: true,
	bump: {
		files: [
			'./test/src-test/package.json',
			'./test/src-test/manifest.json'
		]
	},
	copy: [
		{
			baseFolder: 'assets',
			items: [
				'imgs-others'
			]
		}, {
			baseFolder: 'bundles',
			items: [
				''
			]
		}
	],	
	replace: {
		css: {
			files: 'index.html',
			commentRegex: ['<!--styles!--->((.|\n)*)<!--styles!--->'],
			with: ['assets/style.min.css']
		},
		js: {
			files: 'index.html',
			commentRegex: ['<!--js!--->((.|\n)*)<!--js!--->'],
			with: ['bundle.js']
		}
	}
	vulcanize: {
		srcTarget: 'index.html',
		buildTarget: 'index.html',
		conf: {
			stripComments: true,
			inlineScripts: true,
			inlineStyles: true,
			excludes: ['bundle.js']
		}
	}
};
```

With this situation we have also the possibility to use the power of `webpack` about ***bundling***, with multiple `entry` and multiple `output` and also we leave the error handling to `webpack`:

```javascript 
// webpack.config.js
module.exports = {
		entry: {
           main: './test/src-test/app/index.js',
           vendors: ['array-from', 'fetch']
                },   
		output: {
			// Make sure to use [name] or [id] in output.filename
			//  when using multiple entry points
			path: './test/src-test/',
			filename: '[name].bundle.js'
		},
		devtool: 'source-map',
		module: {
			loaders: [{
				test: /\.js?$/,
				// exclude: /(node_modules|bower_components)/,
				exclude: ['node_modules', 'test/bundle.js', 'test/build'],
				loader: 'babel-loader',
				query: {
					presets: ['es2015'],
					plugins: ['transform-es2015-spread', 'syntax-object-rest-spread', 'transform-object-rest-spread']
				}
			}]
		}
	}
```

Also, we can **warn** the user when `output.path` (`webpack.config.js`) is different from `buildFolder` (`kubozer.conf.js`).
