### ISSUE TITLE
Add `--watch` and `watch()` method 

### ISSUE THREAD

**Issue by LasaleFamine** [contactlab/kubozer#27]
For watching ES6 files with: 
 - webpack-dev-server

Like: [vue-cli](https://github.com/vuejs/vue-cli/blob/master/lib/server.js)

Other proposal? @contactlab/contactlab-frontend-engineers

**Comment by equinusocio** [comment]
It doesn't already watch js files?

**Comment by LasaleFamine** [comment]
@equinusocio nope. Only `--build` and `--bump` are the available commands at the moment.
