### ISSUE TITLE
Add the possibility to concatenate --build and --bump command line arguments

### ISSUE THREAD

**Issue by pferretti** [contactlab/kubozer#47]
Actually to build and bump we need to launch kubozer two times:

```
kubozer --bump
kubozer --build
```

It would be nice to have the possibiliy to launch kubozer with:

`kubozer --bump --build`

**Comment by LasaleFamine** [comment]
This can be changed to "**Add the possibility to concatenate commands**" for every command of `kubozer`. What do you think?

**Comment by StefanoMagrassi** [comment]
@LasaleFamine nice to have, but we must guarantee the right execution order of the commands. 

cli.js needs some fine tuning...
