### ISSUE TITLE
Spaces instead of tabs (please...)

### ISSUE THREAD

**Issue by StefanoMagrassi** [contactlab/kubozer#62]
@LasaleFamine please, let Kubozer use spaces instead of tabs for indentation...

Super easy with XO

```json
"xo": {
  "space": true
}
```

**Comment by LasaleFamine** [comment]
[I agree, let's change this setting.](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/)

This is related to #63 so I think we can make a PR to just switch this and add the proper `.editorconfig`.

**Comment by StefanoMagrassi** [comment]
resolved by #67
