### ISSUE TITLE
npmignore

### ISSUE THREAD

**Issue by StefanoMagrassi** [contactlab/kubozer#83]
It should be added a `.npmignore` in order to keep the package leaner when installed

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by LasaleFamine** [comment]
Can we use the `.gitignore`?

**Comment by StefanoMagrassi** [comment]
@LasaleFamine nope. Git ignorered resources are out of version control, npm ignorered ones are instead not published on npm repository, but always versioned. 

Thinks like the *test* or *src* folders are useless when the package is installed as dependency.

Check the link I poster for further info.

Please note that if you have a .npmignore file in your repo the .gitignore file is "ignorered" by npm on publish, so the same file content has to be rewritten in the . npmignore file

**Comment by LasaleFamine** [comment]
Why not use the simple [files](https://docs.npmjs.com/files/package.json#files) property of the `package.json` to select the "needed" folders? Like just the `dist` folder?

**Comment by StefanoMagrassi** [comment]
@LasaleFamine blacklist vs. whitelist

I prefer to have a list of ignored files ("blacklist") rather then a list of included files ("whitelist"). If the number grows is more difficult to track.

Beside this, it's just a matter of math ;)
If the ignored list is greater than included list .npmignore is better otherwhise go with the files key in package.json
