### ISSUE TITLE
Remove `webpack.config.js`

### ISSUE THREAD

**Issue by LasaleFamine** [contactlab/kubozer#85]
I'm thinking, we can make `kubozer` more opinionated removing the `webpack.config.js` and implicit "hard-code" the configuration within our code-base (maybe a separate file as well, of course).

With this we can expose the minimal configuration (also fixing the current configuration file and making it simple) only with our `kubozer.conf.js`.

What do we think? @pferretti @StefanoMagrassi @moebiusmania @Arual90

**Comment by StefanoMagrassi** [comment]
@LasaleFamine maybe we can have a default configuration hard-coded in the source, but extendable/overwrittable through kubozer.conf file.

**Comment by pferretti** [comment]
@LasaleFamine I agree with @StefanoMagrassi : with an hardcoded overwrittable configuration we can handle a more versatile configuration
