### ISSUE TITLE
Uncaught Error: Module build failed: 

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/kubozer#88]
On https://account.clab-dev.com/ you will see a blank page, open the terminal to read the message: 

```
bundle.js:5354 Uncaught Error: Module build failed: Error: Couldn't find preset "env" relative to directory "/var/jenkins_home/workspace/AccountCentral/account-central-ui-build-bump/node_modules/kubozer"
```

On jenkins the build proceed without throwing errors but generate a non-working results, cloning the project locally and launching the build command it goes throught the build correctly but I got that error popping out via the Webpack notfier tool, so maybe is something related to it.

**Comment by StefanoMagrassi** [comment]
This was a bug related to the dependencies declared in the project's package.json and not a Kubozer one.
